server:
  port: 8001

spring:
  application:
    name: service-producer

  sleuth:
      web:
          client:
            enabled: true
      sampler:
          probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
      base-url: http://mysqlhost:9411/ # 指定了 Zipkin 服务器的地址

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
  # 心跳检测检测与续约时间
  # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2