server:
  port: 14000

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: producer_service
          uri: lb://SERVICE-PRODUCER
          order: 0
          predicates:
            - Path=/hello1/**
          filters:
            - name: Hystrix
              args:
                ## 熔断HystrixCommand 的名字
                name: fallbackcmd
                ## 熔断的fallback 对应的 uri，这里的 uri 仅支持 forward: schemed 的
                fallbackUri: forward:/fallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

## actuator监控
management:
  endpoints:
    web:
      exposure:
        include: info,health,beans,env,metrics
